<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Vofox-Sebastian" name="com.Home.Associate_Home" tests="3" failures="0" timestamp="19 Oct 2018 15:42:39 GMT" time="54.258" errors="1">
  <testcase name="TCBA01101" time="4.103" classname="com.Home.Associate_Home"/>
  <testcase name="TCBA01103" time="2.408" classname="com.Home.Associate_Home"/>
  <testcase name="TCBA01102" time="47.747" classname="com.Home.Associate_Home">
    <error type="java.lang.AssertionError" message="Timeout during waiting for element: &#039;//span[contains(text(),&#039;26&#039;)]&#039;">
      <![CDATA[java.lang.AssertionError: Timeout during waiting for element: '//span[contains(text(),'26')]'
	at com.Library.UtilityClass.waitFor(UtilityClass.java:256)
	at com.Library.UtilityClass.click(UtilityClass.java:168)
	at com.Home.Associate_Home.TCBA01102(Associate_Home.java:139)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1123)
	at org.testng.TestNG.run(TestNG.java:1031)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- TCBA01102 -->
</testsuite> <!-- com.Home.Associate_Home -->
